### ISSUE TITLE
Infografía "HILOS"   Fernando Miguel López.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/infografia-de-hilos-Ferch0419#2]
[Infografía Hilos Fernando Miguel López.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Ferch0419/files/6474808/Infografia.Hilos.Fernando.Miguel.Lopez.pdf)

**Comment by MariaC232** [comment]
Calificación: 20% 
Excelente trabajo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
